# Generated by Django 4.2.6 on 2024-02-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenddata',
            name='task_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='backenddata',
            name='user_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
