# Generated by Django 4.2.6 on 2024-02-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
