# Generated by Django 4.2.6 on 2024-01-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='network_biases',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='network_weights',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
