# Generated by Django 4.2.6 on 2024-01-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_row_network_biases_row_network_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='network_biases',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='row',
            name='network_weights',
            field=models.CharField(max_length=1000000),
        ),
    ]
