# Generated by Django 4.2.6 on 2024-02-01 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_backenddata_task_id_alter_backenddata_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackendData',
        ),
    ]
