# Generated by Django 4.2.6 on 2024-02-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_quiz_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdescription',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
