# Generated by Django 4.2.6 on 2024-01-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_taskdescription_iterations_slider_visibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdescription',
            old_name='normalization',
            new_name='normalization_visibility',
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='name',
            field=models.CharField(default='Linear Regression', max_length=200),
            preserve_default=False,
        ),
    ]
