# Generated by Django 4.2.6 on 2024-01-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_row_network_biases_alter_row_network_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='user_id',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
    ]
