# Generated by Django 4.2.6 on 2024-01-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_normalization_taskdescription_normalization_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='code_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='code_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='code_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
