# Generated by Django 4.2.6 on 2024-01-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_row_network_biases_alter_row_network_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='tag',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
