# Generated by Django 4.2.6 on 2024-02-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_taskdescription_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
