# Generated by Django 4.2.6 on 2024-01-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_quiz_code_1_quiz_code_3_quiz_code_4_quiz_code_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
