# Generated by Django 4.2.6 on 2024-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_intro_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdescription',
            name='decision_boundary_visibility',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
