# Generated by Django 4.2.6 on 2024-01-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_row_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='normalization',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
