# Generated by Django 4.2.6 on 2024-01-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_row_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='task_id',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
