# Generated by Django 4.2.6 on 2024-01-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_quiz_code_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
