# Generated by Django 4.2.6 on 2024-01-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_row_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='row',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
