# Generated by Django 4.2.6 on 2024-03-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_taskdescription_decision_boundary_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
