# Generated by Django 4.2.6 on 2024-01-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_row_normalization'),
        ('backend', '0006_taskdescription_alter_row_user_id'),
    ]

    operations = [
    ]
