# Generated by Django 4.2.6 on 2024-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('task_id', models.IntegerField()),
                ('nn', models.BinaryField()),
                ('dataset', models.BinaryField()),
            ],
        ),
    ]
