# Generated by Django 4.2.6 on 2024-01-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge_20240115_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='tag',
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='max_epochs',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='max_layers',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='max_nodes',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='n_inputs',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='n_outputs',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='normalization',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
