# Generated by Django 4.2.6 on 2024-01-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_row_tag_taskdescription_max_epochs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='plots',
            field=models.CharField(default=[], max_length=1000000),
            preserve_default=False,
        ),
    ]
