# Generated by Django 4.2.6 on 2024-01-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_progress_remove_row_plots_taskdescription_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField(unique=True)),
                ('question_1', models.TextField()),
                ('option_1_a', models.TextField()),
                ('option_1_b', models.TextField()),
                ('option_1_c', models.TextField()),
                ('option_1_d', models.TextField()),
                ('answer_1', models.CharField(max_length=200)),
                ('question_2', models.TextField()),
                ('option_2_a', models.TextField()),
                ('option_2_b', models.TextField()),
                ('option_2_c', models.TextField()),
                ('option_2_d', models.TextField()),
                ('answer_2', models.CharField(max_length=200)),
                ('option_3_a', models.TextField()),
                ('option_3_b', models.TextField()),
                ('option_3_c', models.TextField()),
                ('option_3_d', models.TextField()),
                ('answer_3', models.CharField(max_length=200)),
                ('question_4', models.TextField()),
                ('option_4_a', models.TextField()),
                ('option_4_b', models.TextField()),
                ('option_4_c', models.TextField()),
                ('option_4_d', models.TextField()),
                ('answer_4', models.CharField(max_length=200)),
                ('question_5', models.TextField()),
                ('option_5_a', models.TextField()),
                ('option_5_b', models.TextField()),
                ('option_5_c', models.TextField()),
                ('option_5_d', models.TextField()),
                ('answer_5', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='row',
            name='error_list',
        ),
        migrations.RemoveField(
            model_name='row',
            name='network_biases',
        ),
        migrations.RemoveField(
            model_name='row',
            name='network_weights',
        ),
        migrations.AlterField(
            model_name='row',
            name='nn_input',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taskdescription',
            name='dataset',
            field=models.CharField(max_length=200),
        ),
    ]
