# Generated by Django 4.2.6 on 2024-01-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_progress_remove_row_plots_taskdescription_dataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='minidata',
            field=models.BinaryField(default=b'\x00', max_length=1000000),
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
