# Generated by Django 4.2.6 on 2024-01-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_quiz_remove_row_error_list_remove_row_network_biases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='error_list',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='network_biases',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='network_weights',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
