# Generated by Django 4.2.6 on 2024-01-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_row_minidata_taskdescription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='minidata',
            field=models.CharField(default=' ', max_length=1000000),
        ),
    ]
