# Generated by Django 4.2.6 on 2024-01-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_row_minidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='minidata',
            field=models.BinaryField(default=b'', max_length=1000000),
        ),
    ]
