# Generated by Django 4.2.6 on 2024-01-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_row_minidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='minidata',
            field=models.CharField(default='[]', max_length=1000000),
        ),
    ]
