# Generated by Django 4.2.6 on 2024-01-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_progress_feature_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='minidata',
            new_name='games_data',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='network_setup',
            new_name='network_input',
        ),
        migrations.RemoveField(
            model_name='row',
            name='error_list',
        ),
        migrations.RemoveField(
            model_name='row',
            name='network_biases',
        ),
        migrations.RemoveField(
            model_name='row',
            name='network_weights',
        ),
        migrations.RemoveField(
            model_name='row',
            name='nn_input',
        ),
        migrations.AddField(
            model_name='progress',
            name='network_biases',
            field=models.CharField(default=[], max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='network_weights',
            field=models.CharField(default=[], max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
