# Generated by Django 4.2.6 on 2024-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_minidata_row_games_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='progress_pk',
            field=models.IntegerField(null=True),
        ),
    ]
