# Generated by Django 4.2.6 on 2024-01-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_quiz_answer_1_alter_quiz_answer_2_and_more'),
        ('backend', '0017_row_progress_pk'),
    ]

    operations = [
    ]
