# Generated by Django 4.2.6 on 2023-10-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_rate', models.FloatField(max_length=20)),
                ('epochs', models.IntegerField()),
                ('network_setup', models.CharField(max_length=200)),
                ('nn_input', models.CharField(max_length=2000)),
                ('action', models.IntegerField()),
                ('error_list', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]